export const columns = [
  { key: "lead_id", title: "Lead Id", className: "" },
  // { key: "location", title: "Location", className: "max-w-24 overflow-x-hidden" },
  { key: "recording_id", title: "Recording Id", className: "" },
  { key: "start_time", title: "Start Time", className: "" },
  { key: "length_in_sec", title: "Duration (sec)", className: "" },
  { key: "status", title: "Status" },
  { key: "user", title: "User", className: "" },
  { key: "phone_number", title: "Phone Number", className: "" },
  { key: "actions", title: "Actions", className: "" },
];

export const statusOptions = [
  "A",
  "AA",
  "AB",
  "ADAIR",
  "ADC",
  "ADCT",
  "AFAX",
  "AFTHRS",
  "AL",
  "AM",
  "B",
  "CALLBK",
  "CBHOLD",
  "DAIR",
  "DC",
  "DEC",
  "DNC",
  "DNCC",
  "DNCL",
  "DROP",
  "ERI",
  "INCALL",
  "IQNANQ",
  "IVRXFR",
  "LRERR",
  "LSMERG",
  "MAXCAL",
  "MLINAT",
  "N",
  "NA",
  "NANQUE",
  "NEW",
  "NI",
  "NP",
  "PDROP",
  "PM",
  "PU",
  "QCFAIL",
  "QUEUE",
  "QVMAIL",
  "RQXFER",
  "SALE",
  "SVYCLM",
  "SVYEXT",
  "SVYHU",
  "SVYREC",
  "SVYVM",
  "TIMEOT",
  "XDROP",
  "XFER",
];
