name: DEPLOY TO SERVER

# Trigger this workflow on push or pull request events
on:
  push:
    branches: [master]

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_PRIVATE_KEY }}
      - name: Connect and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5 root@91.107.194.217 << EOF
            cd /root/monorepo/projects/dialer-portal
            git pull origin master
            pnpm install
          EOF
